package com.example.ai

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.ResponseBody
import retrofit2.Retrofit
import retrofit2.converter.kotlinx.serialization.asConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import retrofit2.http.Streaming
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.example.BuildConfig

@Serializable
data class GenerateContentRequest(
    val contents: List<Content>,
    val generationConfig: GenerationConfig? = null,
    val tools: List<JsonObject>? = null,
    val systemInstruction: Content? = null
)

@Serializable
data class Content(
    val parts: List<Part>
)

@Serializable
data class Part(
    val text: String? = null
)

@Serializable
data class GenerationConfig(
    val temperature: Float? = null,
    val topP: Float? = null,
    val topK: Int? = null
)

@Serializable
data class GenerateContentResponse(
    val candidates: List<Candidate>? = null
)

@Serializable
data class Candidate(
    val content: Content? = null
)

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GenerateContentRequest
    ): GenerateContentResponse
}

object RetrofitClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .readTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .writeTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .build()

    val service: GeminiApiService by lazy {
        val json = Json { ignoreUnknownKeys = true }
        val retrofit = Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(json.asConverterFactory("application/json".toMediaType()))
            .build()
        retrofit.create(GeminiApiService::class.java)
    }
}

class GeminiService {
    suspend fun analyzeIdea(title: String, description: String, category: String): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Please configure your Gemini API Key in the Secrets panel."
        }
        
        val prompt = """
            Take the following raw idea and transform it into a structured concept.
            Title: ${'$'}title
            Description: ${'$'}description
            Category: ${'$'}category
            
            Provide the response in the following format using markdown:
            **Idea Summary**: Briefly explain the core idea.
            **Why It Matters**: The core value proposition.
            **Potential Users**: Who is this for?
            **Feature Ideas**: 3-5 possible key features.
            **First Steps**: 3 initial steps to start building or executing it.
            **Possible Challenges**: 2 possible problems or hurdles.
            **Estimated Difficulty**: (e.g. Low, Medium, High)
            **Opportunity Score**: (A score out of 100)
        """.trimIndent()

        val request = GenerateContentRequest(
            contents = listOf(Content(
                parts = listOf(Part(text = prompt))
            ))
        )
        try {
            val response = RetrofitClient.service.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: "No response text generated by AI."
        } catch (e: Exception) {
            "Error analyzing idea: ${'$'}{e.message}"
        }
    }
    
    suspend fun askAssistant(query: String, context: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Please configure your Gemini API Key in the Secrets panel."
        }
        
        val systemPrompt = "You are BrainDrop, a futuristic personal thinking workspace and AI assistant. Your goal is to help the user brainstorm, organize, and execute their ideas."
        val prompt = if (context != null) {
            "Context: ${'$'}context\n\nUser Query: ${'$'}query"
        } else {
            query
        }
        
        val request = GenerateContentRequest(
            systemInstruction = Content(parts = listOf(Part(text = systemPrompt))),
            contents = listOf(Content(
                parts = listOf(Part(text = prompt))
            ))
        )
        
        try {
            val response = RetrofitClient.service.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: "No response from BrainDrop AI."
        } catch (e: Exception) {
            "Error connecting to AI: ${'$'}{e.message}"
        }
    }

    suspend fun convertToProject(ideaTitle: String, ideaDescription: String, currentAiResponse: String?): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Please configure your Gemini API Key in the Secrets panel."
        }
        
        val prompt = """
            Turn the following idea into an actionable project plan.
            Idea Title: ${'$'}ideaTitle
            Idea Description: ${'$'}ideaDescription
            Previous Context: ${'$'}{currentAiResponse ?: "None"}
            
            Generate a project plan formatted using markdown:
            **Project Goal**: A clear, 1-2 sentence goal.
            **Milestones**: Break down into 3-5 major phases.
            **Task List**: Actionable tasks for the first milestone.
            **Timeline**: Rough estimated timeline.
            **Next Action**: The absolute first thing the user should do right now.
        """.trimIndent()

        val request = GenerateContentRequest(
            contents = listOf(Content(
                parts = listOf(Part(text = prompt))
            ))
        )
        try {
            val response = RetrofitClient.service.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: "No response text generated by AI."
        } catch (e: Exception) {
            "Error analyzing project: ${'$'}{e.message}"
        }
    }
}
